### ISSUE TITLE
Bug fix for Diglin/Ricardo/Services/SellerAccount.php -> getPlannedArticles()

### ISSUE THREAD

**Issue by magnalister** [diglin/ricardo#1]
The Parameter is wrong and should be of type "PlannedArticlesParameter".

Exception:

Argument 1 passed to Diglin\Ricardo\Services\SellerAccount::getPlannedArticles() must be an instance of Diglin\Ricardo\Managers\SellerAccount\Parameter\PlannedArticleParameter, instance of Diglin\Ricardo\Managers\SellerAccount\Parameter\PlannedArticlesParameter given, called in /Ricardo/Lib/Diglin/Ricardo/Service.php on line 204 and defined in /Ricardo/Lib/Diglin/Ricardo/Services/SellerAccount.php:329

**Comment by sylvainraye** [comment]
Hi @magnalister thank you for your comment. It's fixed.
